[package]
name = "iota-core"
version = "0.2.0-alpha.1"
authors = ["YuWeiWu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Core library of IOTA"
license = "MIT"

[lib]
name = "iota"

[dependencies]
iota-bundle-preview = "0.1"
iota-ternary-preview = "0.1"
iota-signing-preview = "0.1"
iota-crypto-preview = "0.1"
iota-client = { version = "0.5.0-alpha", path = "../iota-client" }
iota-conversion = { version = "0.5.0", path = "../iota-conversion" }

[dev-dependencies]
criterion = "0.3"
rand = "0.7.3"

[[bench]]
name = "benchmark"
harness = false