sudo: false
dist: trusty
language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: beta
    - rust: stable
  fast_finish: true

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check || travis_terminate 1;
  - cargo build --all --release || travis_terminate 1;
  - cargo test --verbose --all --release
